/**
 * Static catalog of Firebird-specific tips rotated on the welcome
 * dashboard. Curated rather than crowdsourced — each line earns its
 * spot by surfacing a non-obvious behaviour, a syntax that newcomers
 * miss, or a sharp edge that bites in production.
 *
 * Adding a tip:
 * - Pick a stable `id` (kebab-case noun phrase). Used as the React key
 *   and as the rotation cursor; never reuse a retired id.
 * - Keep `text` short — a line that fits on one row of the card at
 *   the typical viewport. Two short sentences max.
 * - Set `minVersion` to the integer Firebird major where the feature
 *   first appeared. Omit when the tip applies universally (FB 2.5+).
 * - Add `link` only when the relevant chapter of the Firebird docs is
 *   genuinely useful as a follow-up.
 */

export interface FirebirdTip {
  id: string;
  text: string;
  /** Lowest Firebird major version where the tip applies. Tips with
   *  a higher floor than the active engine are filtered out. */
  minVersion?: number;
  /** Optional documentation URL surfaced as a small "learn more" anchor
   *  next to the tip text. */
  link?: string;
}

export const FIREBIRD_TIPS: readonly FirebirdTip[] = [
  {
    id: 'gen-id-peek',
    text: 'GEN_ID(name, 0) reads a generator without incrementing it — handy for peeking at the current value.',
  },
  {
    id: 'rdb-database',
    text: 'RDB$DATABASE is the one-row system pseudo-table — use SELECT … FROM RDB$DATABASE for any one-shot expression.',
  },
  {
    id: 'rdb-context',
    text: 'RDB$GET_CONTEXT(\'SYSTEM\', \'ENGINE_VERSION\') returns the server version as a string — handy for version-aware scripts.',
  },
  {
    id: 'first-skip',
    text: 'Use SELECT FIRST n SKIP m … to page results without OFFSET. Faster than CTE-based pagination on large tables.',
  },
  {
    id: 'rows-modern',
    text: 'On Firebird 3+, SELECT … ROWS m TO n is the SQL-standard equivalent of FIRST/SKIP — prefer it in new code.',
    minVersion: 3,
  },
  {
    id: 'returning-clause',
    text: 'INSERT … RETURNING <cols> hands the new row back in a single round-trip — no second SELECT needed.',
  },
  {
    id: 'merge-statement',
    text: 'MERGE INTO target USING source ON … WHEN MATCHED / NOT MATCHED is Firebird\'s upsert. Cleaner than the IF EXISTS dance.',
  },
  {
    id: 'execute-block',
    text: 'EXECUTE BLOCK lets you run PSQL on the fly without creating a stored procedure — great for ad-hoc loops.',
  },
  {
    id: 'identity-cols',
    text: 'FB 3+ supports GENERATED BY DEFAULT AS IDENTITY — drop the generator + trigger boilerplate for new PKs.',
    minVersion: 3,
  },
  {
    id: 'boolean-type',
    text: 'BOOLEAN is a first-class type on Firebird 3+. Use TRUE / FALSE / UNKNOWN directly instead of CHAR(1) flags.',
    minVersion: 3,
  },
  {
    id: 'window-functions',
    text: 'Window functions (ROW_NUMBER, RANK, LAG, LEAD) work on FB 3+ — kill the self-join pattern for running totals.',
    minVersion: 3,
  },
  {
    id: 'expr-indices',
    text: 'Expression indexes (CREATE INDEX … COMPUTED BY (...)) let you index UPPER(name) or any expression directly.',
  },
  {
    id: 'partial-indices',
    text: 'Partial indexes (CREATE INDEX … WHERE …) on FB 5+ cut index size for sparse predicates like WHERE active = TRUE.',
    minVersion: 5,
  },
  {
    id: 'in-place-encryption',
    text: 'ALTER DATABASE ENCRYPT WITH … KEY … rewrites pages in the background. Monitor progress via MON$CRYPT_PAGE.',
    minVersion: 3,
  },
  {
    id: 'recompute-stats',
    text: 'After bulk loads, run SET STATISTICS INDEX <idx> to refresh selectivity. The optimizer will thank you.',
  },
  {
    id: 'mon-statements',
    text: 'SELECT * FROM MON$STATEMENTS lists every running statement — useful when a query won\'t come back.',
  },
  {
    id: 'mon-attachments',
    text: 'MON$ATTACHMENTS shows every connection. DELETE FROM MON$ATTACHMENTS WHERE MON$ATTACHMENT_ID = N kicks a hung session.',
  },
  {
    id: 'transactions-default',
    text: 'Isql defaults to SNAPSHOT isolation. Use SET TRANSACTION READ COMMITTED when you need to see other sessions\' commits.',
  },
  {
    id: 'noformatdate',
    text: 'Firebird literal dates are \'YYYY-MM-DD\'. CAST(\'TODAY\' AS DATE) and \'NOW\' work too — handy in defaults and triggers.',
  },
  {
    id: 'computed-by',
    text: 'COMPUTED BY columns are evaluated on read — no storage cost, but every SELECT pays for the expression.',
  },
  {
    id: 'check-constraints',
    text: 'CHECK constraints support subqueries via EXISTS. Use sparingly — they fire on every INSERT/UPDATE.',
  },
  {
    id: 'before-vs-after',
    text: 'BEFORE INSERT triggers can mutate NEW.<col>; AFTER triggers cannot. Pick the right phase the first time.',
  },
  {
    id: 'autonomous-tx',
    text: 'In PSQL, IN AUTONOMOUS TRANSACTION DO … runs a nested transaction. Perfect for audit-log writes.',
  },
  {
    id: 'left-trim-utf',
    text: 'TRIM(BOTH \' \' FROM s) is portable. Avoid LTRIM/RTRIM if you also want a leading-character mask — TRIM(BOTH \'x\' FROM s) handles both.',
  },
  {
    id: 'sweep-interval',
    text: 'Long-running write transactions raise OST (oldest snapshot). Watch MON$DATABASE.MON$OLDEST_SNAPSHOT — high values bloat the database.',
  },
  {
    id: 'gbak-vs-nbackup',
    text: 'gbak is a logical export (portable, slow). nbackup is a page-level snapshot (fast, version-locked). Pick by use case.',
  },
  {
    id: 'pk-vs-unique',
    text: 'PRIMARY KEY auto-creates a unique index. Skip the redundant CREATE UNIQUE INDEX you might be used to from MySQL.',
  },
  {
    id: 'cross-database',
    text: 'Firebird does NOT support cross-database joins. Use EXTERNAL FUNCTION or a federation layer for that workload.',
  },
  {
    id: 'reserved-words',
    text: 'Quoted "lowercase" identifiers stay case-sensitive forever. Stick to UPPERCASE bare identifiers unless you really need quoting.',
  },
  {
    id: 'plan-keyword',
    text: 'SELECT … PLAN (TABLE INDEX(IDX)) lets you hand-feed a plan when the optimizer picks wrong. Last-resort override.',
  },
  {
    id: 'page-size',
    text: 'PAGE_SIZE 8192 is the modern default. 4096 wastes IO; >16k bloats memory. Set it at create-database time — can\'t change live.',
  },
  {
    id: 'force-version',
    text: 'isql -z prints the server build. Mismatched client/server major versions are a top-3 cause of "cryptic" errors.',
  },
];

/** Returns the tips that apply to the given engine major version. A
 *  `null` version (no live connection yet) keeps everything. Stable
 *  order — the rotation cursor relies on this. */
export function filterTipsForVersion(version: number | null): FirebirdTip[] {
  if (version === null) return FIREBIRD_TIPS.slice();
  return FIREBIRD_TIPS.filter((tip) => (tip.minVersion ?? 0) <= version);
}

/** Pulls the engine major out of a free-form `engineVersion` string
 *  (e.g. `"WI-V5.0.1.1469 Firebird 5.0"`). Returns `null` on any
 *  parse miss — the caller treats `null` as "no version filter". */
export function parseEngineMajor(engineVersion: string | null | undefined): number | null {
  if (!engineVersion) return null;
  // The string usually contains "Firebird X.Y" near the end; fall back
  // to a generic digit-pair scan so format drift across versions
  // doesn't accidentally hide every tip.
  const direct = /Firebird\s+(\d+)/i.exec(engineVersion);
  if (direct && direct[1]) return Number(direct[1]);
  const generic = /\b([3-9])\.\d+/.exec(engineVersion);
  if (generic && generic[1]) return Number(generic[1]);
  return null;
}
