// AUTO-GENERATED by `plamenix-ts-gen` (see crates/plamenix-ts-gen).
// DO NOT EDIT BY HAND. Run `just ts-gen` from plamenix-core to refresh.
/* eslint-disable */

// This file has been generated by Specta. Do not edit this file manually.
/**  One live attachment seen via `MON$ATTACHMENTS`. */
export type AttachmentInfo = {
	/**  `MON$ATTACHMENT_ID`. */
	id: number,
	/**  `MON$USER`. */
	user: string,
	/**  `MON$ROLE`, blank string when no explicit role. */
	role: string,
	/**  `MON$REMOTE_ADDRESS`. */
	remoteAddress: string,
	/**  `MON$REMOTE_PROCESS` — friendly name of the client binary. */
	remoteProcess: string,
	/**  `MON$CHARACTER_SET_ID` looked up to its character-set name. */
	characterSet: string,
	/**  `MON$STATE` — 0 idle, 1 active, 2 stalled. */
	state: number,
	/**  `MON$TIMESTAMP` rendered as ISO string. */
	timestamp: string,
	/**  `true` when this attachment is the one querying `MON$ATTACHMENTS`. */
	isSelf: boolean,
};

/**
 *  Handle to a binary BLOB cached server-side. The full body is
 *  fetched on demand via [`crate::DbDriver::fetch_blob`]; the row
 *  payload only carries this small reference so large BLOBs do not
 *  inflate every result row.
 */
export type BlobRef = {
	/**  Opaque identifier — `fetch_blob(session, id)` returns the body. */
	id: string,
	/**  Total BLOB length in bytes, surfaced so the UI can show size. */
	sizeBytes: number,
	/**
	 *  Lower-case hex preview of the first ~32 bytes. Enough to
	 *  drive the table preview chip and the MIME sniffer.
	 */
	peekHex: string,
};

/**  A column description as reported by the driver. */
export type Column = {
	/**
	 *  Column name as reported by the Firebird engine (already
	 *  upper-cased by Firebird unless quoted in the query).
	 */
	name: string,
};

/**  One row from `RDB$RELATION_FIELDS`/`RDB$FIELDS`. */
export type ColumnInfo = {
	/**  Column name as Firebird stores it. */
	name: string,
	/**  Ordinal position within the relation, starting at 0. */
	position: number,
	/**
	 *  Human-readable SQL type string (e.g. `VARCHAR(50)`,
	 *  `TIMESTAMP WITH TIME ZONE`, `BLOB SUB_TYPE TEXT`).
	 */
	sqlType: string,
	/**  `true` when the column allows `NULL`. */
	nullable: boolean,
	/**
	 *  Default-value expression as declared in the DDL, with the
	 *  leading `DEFAULT ` keyword stripped. `None` when no default is
	 *  set. Sourced from `RDB$RELATION_FIELDS.RDB$DEFAULT_SOURCE`
	 *  first (per-column default) and falls back to
	 *  `RDB$FIELDS.RDB$DEFAULT_SOURCE` (domain default).
	 */
	defaultExpr?: string | null,
};

/**
 *  Scalar values produced by Firebird columns.
 * 
 *  The driver returns this typed enum rather than a single `String`
 *  representation so the UI layer can render dates, numbers, and binary
 *  blobs faithfully without re-parsing.
 */
export type ColumnValue = 
/**  SQL `NULL` for this column on this row. */
{ type: "null" } | 
/**  Textual data (CHAR, VARCHAR, BLOB `SUB_TYPE` TEXT). */
{ type: "text"; value: string } | 
/**
 *  64-bit signed integer (SMALLINT, INTEGER, BIGINT).
 * 
 *  Carried as decimal text: the magnitude is the user's data, and a
 *  `BIGINT` past 2^53 cannot survive a JSON number. See
 *  [`plamenix_types::exact_int`].
 */
{ type: "integer"; value: string } | 
/**
 *  Exact fixed-point value (NUMERIC, DECIMAL).
 * 
 *  Carried as decimal text because neither `f64` nor a JSON number
 *  can hold it: Firebird stores these as a scaled 64-bit integer,
 *  and NUMERIC(18,4) — the usual money type — runs past what a
 *  double represents exactly.
 */
{ type: "decimal"; value: string } | 
/**
 *  Double-precision floating point (FLOAT, DOUBLE PRECISION).
 * 
 *  Genuinely approximate, unlike [`Self::Decimal`]: `f64` is the
 *  faithful representation of what Firebird stores.
 */
{ type: "float"; value: number | null } | 
/**  Boolean (FB 3.0+ `BOOLEAN`). */
{ type: "bool"; value: boolean } | 
/**  Reference to a binary BLOB; full body fetched on demand. */
{ type: "blob"; value: BlobRef };

/**
 *  Connection configuration for attaching to a Firebird database.
 * 
 *  Captures every parameter the connect dialog collects, including
 *  encryption-related fields used by Firebird 3+ `DbCrypt` / `KeyHolder`
 *  plugins. Passwords and encryption keys travel through this type but
 *  are never persisted: the connection layer hands them to the driver
 *  and clears its copy as soon as the attach succeeds.
 */
export type ConnectionConfig = {
	/**  Hostname or IP address of the Firebird server. */
	host: string,
	/**  TCP port. Default Firebird port is `3050`. */
	port: number,
	/**  Database path or registered alias on the server. */
	database: string,
	/**  Username to authenticate with. */
	user: string,
	/**  Password to authenticate with. Held in memory only. */
	password: string,
	/**
	 *  Optional encryption key for at-rest-encrypted databases.
	 * 
	 *  The Firebird C API supplies runtime keys through
	 *  `fb_database_crypt_callback`, registered before
	 *  `isc_attach_database`. Upstream rsfbclient `v0.26` does not
	 *  surface that callback; Plamenix ships the binding in the
	 *  vendored `rsfbclient-native` crate under
	 *  `vendor/rsfbclient-native/src/crypt.rs`. `plamenix-db`'s
	 *  connect path calls `set_key(...)` immediately before
	 *  `isc_attach_database` and clears the slot once the attach
	 *  settles, so the bytes do not stay resident between sessions.
	 * 
	 *  A KeyHolder plugin (e.g. IBSurgeon EPF) configured on the
	 *  fbclient install can still supply keys via its own
	 *  `fbcrypt.conf`; both paths coexist and the callback wins when
	 *  both are present (Firebird checks the registered callback
	 *  first).
	 */
	encryption_key?: string | null,
	/**
	 *  Optional override for the `fbclient` library path.
	 * 
	 *  When `None`, Plamenix uses the bundled `fbclient` for the user's
	 *  platform. When `Some`, the path points at a user-supplied library
	 *  (e.g. a different Firebird major version) loaded via
	 *  `rsfbclient`'s `with_dyn_load` builder.
	 */
	fbclient_path?: string | null,
	/**
	 *  Wire charset for the session. `None` falls back to `UTF8`.
	 * 
	 *  Accepted values match `rsfbclient_core::Charset::from_str`:
	 *  `UTF8`, `ISO8859_1`..`ISO8859_7`, `ISO8859_13`, `WIN1250`..`WIN1258`
	 *  (no `1255`), `ASCII`, `KOI8R`, `KOI8U`, `EUCJP`, `BIG5_2003`.
	 *  Picked at attach time and applied to every string column the
	 *  driver decodes for the rest of the session — affects how legacy
	 *  `WIN1250` databases render Croatian / Czech / Polish text.
	 */
	charset?: string | null,
	/**
	 *  If `true`, refuse to connect to a database whose `MON$CRYPT_STATE`
	 *  is not `1` (encrypted). Defends against accidental connections to
	 *  unencrypted environments when the user expects an encrypted one.
	 */
	encryption_required?: boolean,
	/**
	 *  If `true`, attach via Firebird's embedded engine — the
	 *  `database` field is treated as a local file path; `host` and
	 *  `port` are ignored. Exclusive access only (no other process may
	 *  be holding the file open).
	 */
	embedded?: boolean,
};

/**  Encryption state of an attached Firebird database. */
export type CryptState = 
/**  Database file is unencrypted. */
"unencrypted" | 
/**
 *  Database file is encrypted; the host satisfied the
 *  `KeyHolder` callback during attach.
 */
"encrypted" | 
/**  `ALTER DATABASE DECRYPT` is in progress. */
"decrypt_in_progress" | 
/**  `ALTER DATABASE ENCRYPT` is in progress. */
"encrypt_in_progress";

/**  One alias entry from a Firebird `databases.conf` file. */
export type DatabaseAlias = {
	/**  The alias name (left-hand side of `name = path`). */
	alias: string,
	/**  The database path (right-hand side). */
	path: string,
};

/**
 *  Snapshot of `MON$DATABASE`, plus the live attachment and statement
 *  lists for the dashboard.
 * 
 *  All counters are stamped at query time and not refreshed; the UI
 *  pulls a new [`DatabaseStats`] when the user clicks "Refresh".
 */
export type DatabaseStats = {
	/**  `MON$DATABASE` row plus a couple of derived counters. */
	database: MonDatabase,
	/**  All live attachments visible to the connected user. */
	attachments: AttachmentInfo[],
	/**  All live statements visible to the connected user. */
	statements: StatementInfo[],
};

/**  One user-defined domain. */
export type DomainInfo = {
	/**  Domain name. */
	name: string,
	/**  Rendered SQL type (e.g. `VARCHAR(50)`, `INTEGER`). */
	sqlType: string,
	/**  `true` when the domain allows NULL. */
	nullable: boolean,
};

/**  One sequence / generator. */
export type GeneratorInfo = {
	/**  Generator name. */
	name: string,
	/**
	 *  Current value, sampled via `GEN_ID(<name>, 0)` at describe-schema
	 *  time. Surfaced by the welcome dashboard and the inline editor in
	 *  the schema browser. `0` for a freshly created generator that has
	 *  never been incremented.
	 * 
	 *  Carried as decimal text: a Firebird generator is a `BIGINT` and
	 *  spans the full 64-bit range. See [`exact_int`].
	 */
	currentValue: string,
};

/**  One entry from the per-profile SQL query history. */
export type HistoryEntry = {
	/**  Auto-incrementing primary key from the local SQLite store. */
	id: number,
	/**  Profile this entry belongs to. */
	profileId: string,
	/**  Statement text as executed. */
	sql: string,
	/**  Epoch milliseconds (UTC) when the statement ran. */
	executedAt: number,
	/**  Wall-clock duration in milliseconds. */
	durationMs: number,
	/**  `ok` or `err`. */
	status: string,
	/**  Error string when `status` is `err`. */
	error: string | null,
	/**  Row count for SELECT-like outcomes; `None` for DML/DDL. */
	rowCount: number | null,
	/**
	 *  Free-form user-assigned label. `None` means the entry is shown
	 *  by its SQL preview only; a non-empty string renders as a chip
	 *  above the preview in the history panel.
	 */
	label: string | null,
};

/**
 *  Result of `db_list_aliases`. `source_path` is the path of the parsed
 *  `databases.conf`, or `None` when no candidate file was found on the
 *  local filesystem (e.g. when the IDE is running on a different host
 *  than the Firebird server).
 */
export type ListAliasesResult = {
	/**  Absolute path of the `databases.conf` that was parsed. */
	sourcePath: string | null,
	/**  Aliases parsed from the file. */
	aliases: DatabaseAlias[],
};

/**
 *  One row of `MON$DATABASE` plus the corresponding `MON$IO_STATS` /
 *  `MON$RECORD_STATS` totals at the database level.
 * 
 *  Field names mirror the Firebird metadata column names with the
 *  `MON$` prefix dropped and converted to `snake_case` for serde + Specta.
 */
export type MonDatabase = {
	/**  `MON$DATABASE_NAME` — full database path on the server. */
	name: string,
	/**  `MON$PAGE_SIZE`. */
	pageSize: number,
	/**  `MON$PAGES` — pages currently allocated. */
	pages: number,
	/**  `MON$OLDEST_TRANSACTION` (OIT). */
	oldestTransaction: number,
	/**  `MON$OLDEST_ACTIVE` (OAT). */
	oldestActive: number,
	/**  `MON$OLDEST_SNAPSHOT` (OST). */
	oldestSnapshot: number,
	/**  `MON$NEXT_TRANSACTION` (Next). */
	nextTransaction: number,
	/**  `MON$SWEEP_INTERVAL`. */
	sweepInterval: number,
	/**  `true` when `MON$FORCED_WRITES = 1`. */
	forcedWrites: boolean,
	/**  `true` when `MON$READ_ONLY = 1`. */
	readOnly: boolean,
	/**  `MON$SQL_DIALECT` — usually `3`. */
	sqlDialect: number,
	/**  `MON$CREATION_DATE` rendered as ISO string. */
	creationDate: string,
	/**  `MON$BACKUP_STATE` — 0 normal, 1 stalled, 2 merge. */
	backupState: number,
	/**  `MON$SHUTDOWN_MODE` — 0 online, 1 multi, 2 single, 3 full. */
	shutdownMode: number,
	/**  `MON$OWNER` — database owner. */
	owner: string,
	/**  Firebird engine version reported by `rdb$get_context`. */
	serverVersion: string,
	/**  `MON$ODS_MAJOR`. */
	odsMajor: number,
	/**  `MON$ODS_MINOR`. */
	odsMinor: number,
	/**  Total reads charged to the database (`MON$IO_STATS` aggregate). */
	reads: number,
	/**  Total writes charged to the database. */
	writes: number,
	/**  Total fetches. */
	fetches: number,
	/**  Total marks. */
	marks: number,
};

/**  One stored procedure. */
export type ProcedureInfo = {
	/**  Procedure name as Firebird stores it. */
	name: string,
	/**  Number of declared input parameters. */
	inputCount: number,
	/**
	 *  Number of declared output parameters. `0` for executable
	 *  procedures with no `RETURNS` clause.
	 */
	outputCount: number,
};

/**  A saved connection profile. */
export type Profile = {
	/**  Stable identifier. */
	id: ProfileId,
	/**  Human-readable label shown in the profile picker. */
	name: string,
	/**  Firebird server hostname / IP. */
	host: string,
	/**  TCP port. Defaults to 3050 in the connect dialog. */
	port: number,
	/**  Database path or registered alias. */
	database: string,
	/**  Username. */
	user: string,
	/**
	 *  Keyring account key (under the edition's keyring service) where
	 *  the password is stored. `None` means "ask the user every time".
	 */
	passwordKeyringRef: string | null,
	/**
	 *  Keyring account key for an encryption key, when targeting an
	 *  at-rest-encrypted database.
	 */
	encryptionKeyKeyringRef: string | null,
	/**
	 *  When true, the host refuses to connect to a database whose
	 *  `MON$CRYPT_STATE` is not `1`.
	 */
	encryptionRequired: boolean,
	/**
	 *  When true, the host uses rsfbclient's pure-Rust backend instead
	 *  of the bundled native fbclient.
	 */
	pureRust: boolean,
	/**
	 *  Optional accent-palette id (`blue`, `amber`, `rose`, …) the UI
	 *  uses to tint this profile's tabs and status dot. Lets users
	 *  visually distinguish dev/staging/prod connections. `None` means
	 *  "no tint, use the default theme accent".
	 */
	color?: string | null,
	/**
	 *  Epoch milliseconds (UTC) when this profile was first saved.
	 *  Stable across edits; the store preserves the original value
	 *  when overwriting an existing entry. Older profile files that
	 *  pre-date this field deserialise with `0`.
	 */
	createdAt?: number,
	/**
	 *  Epoch milliseconds (UTC) of the most recent successful connect
	 *  using this profile. `None` until the user has connected at
	 *  least once. Surfaces in the profile picker as a relative
	 *  "Last used Xm ago" hint.
	 */
	lastUsedAt?: number | null,
	/**
	 *  Epoch milliseconds (UTC) of the most recent explicit
	 *  disconnect against this profile. Stamped only when the user
	 *  (or the app on their behalf) calls Disconnect — not on tab
	 *  close or app shutdown. Pairs with `last_used_at` so the
	 *  profile picker can render "Used X · Disconnected Y" hints.
	 */
	lastDisconnectedAt?: number | null,
	/**
	 *  Optional absolute path to the Firebird native client library
	 *  (`libfbclient.dylib` / `.so` / `fbclient.dll`). When set,
	 *  `plamenix-db` hands it to `rsfbclient::with_dyn_load` so the
	 *  session attaches via this specific build (useful when multiple
	 *  Firebird versions are installed side-by-side). `None` falls
	 *  back to the usual `PLAMENIX_FBCLIENT_PATH` env chain. Ignored
	 *  entirely when `pure_rust` is `true`.
	 */
	fbclientPath?: string | null,
	/**
	 *  Wire charset for the session. `None` falls back to `UTF8`.
	 *  Accepted values match `rsfbclient_core::Charset::from_str` —
	 *  see `plamenix_types::ConnectionConfig::charset` for the list.
	 */
	charset?: string | null,
	/**
	 *  `true` when the profile attaches via Firebird's embedded engine
	 *  (the `database` field is a local file path; `host`/`port` are
	 *  ignored). Defaults to `false` so legacy profiles continue to
	 *  behave as remote-server connections.
	 */
	embedded?: boolean,
};

/**
 *  Stable identifier for a profile across renames.
 * 
 *  Allocated with `ProfileId::new()` on first save and immutable after.
 */
export type ProfileId = string;

/**  The shape returned by [`crate::DbDriver::execute`]. */
export type QueryResult = 
/**  A `SELECT` (or similar) result: column metadata and rows. */
({ Rows: {
	/**  Column descriptions in declaration order. */
	columns: Column[],
	/**  Rows produced. May be truncated when `truncated` is `true`. */
	rows: Row[],
	/**
	 *  `true` when the caller injected a row cap (via
	 *  [`inject_row_limit`]) and the server returned at least one
	 *  row beyond the cap. The `rows` field is already trimmed to
	 *  the cap; this flag tells the UI to surface a "truncated"
	 *  hint and offer a re-run without the cap.
	 */
	truncated?: boolean,
} }) & { Affected?: never } | 
/**  A DML / DDL statement that returned no rows. */
({ Affected: {
	/**  Number of rows affected, when reported by the driver. */
	rows: number,
} }) & { Rows?: never };

/**  A single result row. */
export type Row = {
	/**  Cell values in column order. */
	cells: ColumnValue[],
};

/**
 *  Catalogue describing the schema visible to a Firebird session.
 * 
 *  Returned by `DbDriver::describe_schema`. Includes tables and views
 *  (filtered by `RDB$SYSTEM_FLAG = 0`); system relations are excluded.
 */
export type Schema = {
	/**
	 *  All non-system tables and views the connection can see, sorted
	 *  by name and each carrying their column list.
	 */
	tables: TableInfo[],
	/**  Stored procedures from `RDB$PROCEDURES` (system flag = 0). */
	procedures?: ProcedureInfo[],
	/**  Triggers from `RDB$TRIGGERS` (system flag = 0). */
	triggers?: TriggerInfo[],
	/**  Sequences / generators from `RDB$GENERATORS`. */
	generators?: GeneratorInfo[],
	/**
	 *  User-defined domains from `RDB$FIELDS` (excluding the auto
	 *  `RDB$N`-named domains that back regular columns).
	 */
	domains?: DomainInfo[],
};

/**
 *  Identifier for an active Firebird session.
 * 
 *  A session is created when [`ConnectionConfig`] is attached to a
 *  Firebird server and dropped when the owning tab closes or the session
 *  expires. Session identifiers are opaque UUIDs and must not be parsed
 *  or generated outside the connection layer.
 */
export type SessionId = string;

/**  One live statement seen via `MON$STATEMENTS`. */
export type StatementInfo = {
	/**  `MON$STATEMENT_ID`. */
	id: number,
	/**  `MON$ATTACHMENT_ID` that owns the statement. */
	attachmentId: number,
	/**  `MON$STATE` — 0 idle, 1 active, 2 stalled. */
	state: number,
	/**  `MON$TIMESTAMP` rendered as ISO string. */
	timestamp: string,
	/**  `MON$SQL_TEXT` — the prepared SQL for the statement. */
	sqlText: string,
};

/**
 *  Outcome of one statement in a multi-statement batch.
 * 
 *  The Tauri / web command handler splits the incoming SQL into
 *  individual statements with [`split_statements`], executes each, and
 *  returns one of these per statement. Execution stops at the first
 *  failure so the user sees exactly which statement broke the batch.
 */
export type StatementOutcome = 
/**  Statement ran successfully. */
{ status: "ok"; 
/**
 *  The exact SQL text that was executed (with surrounding
 *  whitespace trimmed, semicolon stripped).
 */
sql: string; 
/**  Driver-level result. */
result: QueryResult; 
/**  Wall-clock duration in milliseconds. */
durationMs: number } | 
/**  Statement failed; the batch aborted after this entry. */
{ status: "err"; 
/**  The SQL text that was attempted. */
sql: string; 
/**  Stringified driver error. */
error: string; 
/**
 *  Wall-clock duration in milliseconds (typically near-zero for
 *  validation failures).
 */
durationMs: number };

/**
 *  Identifier for an open UI tab.
 * 
 *  Each tab owns its own [`SessionId`] and per-tab state (selection,
 *  filters, pagination, scroll position). Tab identifiers are stable
 *  across tab reorders.
 */
export type TabId = string;

/**  One row from `RDB$RELATIONS` plus its columns. */
export type TableInfo = {
	/**
	 *  Relation name as Firebird stores it (already trimmed of CHAR
	 *  padding).
	 */
	name: string,
	/**  Whether this is a persistent table or a view. */
	kind: TableKind,
	/**  Column metadata, in declared position order. */
	columns: ColumnInfo[],
	/**
	 *  Primary-key column names, in declared segment order. Empty for
	 *  tables without a `PRIMARY KEY` constraint or for views.
	 */
	primaryKey?: string[],
};

/**  Persistent table vs view, derived from `RDB$RELATION_TYPE`. */
export type TableKind = 
/**  Persistent base table. */
"table" | 
/**  View. */
"view";

/**
 *  Result of a `db_test_connection` request.
 * 
 *  Always returns shape (no thrown error on a clean failure); the `ok`
 *  flag distinguishes success from a reported failure. `firebird_version`
 *  is best-effort and comes from
 *  `rdb$get_context('SYSTEM', 'ENGINE_VERSION')` when the attach
 *  succeeded.
 */
export type TestConnectionResult = {
	/**  `true` when the attach succeeded. */
	ok: boolean,
	/**  Firebird engine version reported by the server, when reachable. */
	firebirdVersion: string | null,
	/**  Failure message when `ok` is `false`. */
	error: string | null,
	/**
	 *  Wall-clock duration of the attach (and version probe) in
	 *  milliseconds.
	 */
	durationMs: number,
};

/**  One trigger row. */
export type TriggerInfo = {
	/**  Trigger name. */
	name: string,
	/**
	 *  Relation the trigger fires on (empty for database-level
	 *  triggers).
	 */
	relation: string,
	/**
	 *  Trigger type per `RDB$TRIGGERS.RDB$TRIGGER_TYPE`. Decoded by the
	 *  UI into BEFORE/AFTER + INSERT/UPDATE/DELETE labels.
	 */
	triggerType: number,
	/**
	 *  `true` when the trigger is currently active (the inverse of
	 *  `RDB$TRIGGER_INACTIVE`).
	 */
	active: boolean,
};

/**  How a session's explicit transactions are started. */
export type TxConfig = {
	/**  Isolation level. Defaults to read-committed. */
	isolation: TxIsolation,
	/**
	 *  Lock resolution. Defaults to `NoWait` so the UI reports a
	 *  conflict instead of blocking on it indefinitely.
	 */
	locking: TxLocking,
};

/**
 *  Isolation level for an explicit transaction.
 * 
 *  Firebird's third level, `consistency` (snapshot table stability), is
 *  intentionally not offered: it takes table-level locks, so one user
 *  selecting it from a dropdown can stall a shared server.
 */
export type TxIsolation = 
/**
 *  Sees other transactions' commits as they happen. The cheapest
 *  option and the right default for interactive work.
 */
"readCommitted" | 
/**
 *  A stable view of the database from the moment the transaction
 *  started — Firebird's `concurrency`. Needed for a consistent
 *  multi-statement export; holds the snapshot, and therefore the
 *  oldest active transaction, for as long as it is open.
 */
"snapshot";

/**  What a statement does when it hits a lock another transaction holds. */
export type TxLocking = 
/**
 *  Block until the other transaction finishes. With `None` the wait
 *  is unbounded, which is how an editor ends up frozen on a row
 *  somebody else is editing.
 */
{ kind: "wait"; timeoutSecs: number | null } | 
/**
 *  Fail immediately on conflict. Predictable for interactive use,
 *  and the reason a conflicting statement reports rather than hangs.
 */
{ kind: "noWait" };

/**  When a session commits the statements the user runs. */
export type TxMode = 
/**
 *  Commit after every statement. The default, and what a user who
 *  has not thought about transactions expects.
 */
"autocommit" | 
/**
 *  Hold statements in one transaction until the user commits or
 *  rolls back. Nothing is written until they say so — including
 *  DDL, which Firebird makes transactional.
 */
"manual";

/**  A session's current transaction state, as the UI shows it. */
export type TxStatus = {
	/**  Autocommit or manual. */
	mode: TxMode,
	/**  Settings explicit transactions are started with. */
	config: TxConfig,
	/**
	 *  Whether an explicit transaction is currently open. Always false
	 *  in autocommit.
	 */
	open: boolean,
	/**
	 *  Statements run since the transaction opened, so the indicator can
	 *  say what would be lost to a rollback.
	 */
	pendingStatements: number,
	/**
	 *  How long the transaction has been open, in milliseconds. The
	 *  number worth watching: a transaction open for minutes is holding
	 *  back garbage collection for the whole database.
	 */
	ageMs: number,
};
